#!/bin/sh

# run KM survival analysis

# Input tab-delimited file should contain following information and was generated by running dataPrepare.sh

# OS. Overall survival status "0" and "1" represents "alive" and "dead" resepctively

# OS.time. Overall survival time in days

# radiation_thearpy. "YES" and "NO" represented by 0 and 1

# PDHA1. gene expression top10%(high expression) and rest90%(low expression) represented by 1 and 2

dataPrepare()
{

	cut -f2-6 $1.tsv | sed '1d' - | \
	awk -F '\t' '{if($2!="" && $3=="NO") print $1 "\t" $2 "\t" "1" "\t" $4 "\t" $5; else if($2!="" && $3=="YES") print $1 "\t" $2 "\t" "0" "\t" $4 "\t" $5}' - | \
	sort -k2nr - > $1.rawdata.tsv

	high=$(expr $(wc -l "$1".rawdata.tsv | cut -d ' ' -f1) / 10 + 1)

	awk -v n=$high -F '\t' '{if(NR <= n) print $1 "\t" "1" "\t" $3 "\t" $4 "\t" $5; else print $1 "\t" "2" "\t" $3 "\t" $4 "\t" $5}' $1.rawdata.tsv > $1.tmp

	echo -e 'patient_id\tPDHA1\tradiation_therapy\tOS.time\tOS' | cat - $1.tmp > $1.survival.tsv

	#rm $1.tsv 
	
	rm $1.tmp
}

declare -a arr=("GBM" "LUNG" "COAD" "PRAD" "LIHC" "SKCM" "STAD" "BRCA")

for cancer in "${arr[@]}"; do dataPrepare "$cancer"; done
